### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by AmandaGAnderson** [VikeLabs/RateMyCoop#2]
### Task
As a developer and user I would like to be able to navigate the website.

### Acceptance Criteria
- RateMyCoop name
- Descriptive icons or words that link to blank pages for searching and reviewing

### MockUp
![Home Mockup](https://github.com/VikeLabs/RateMyCoop/blob/main/Mockups/Home%20Page(Caelum%20V1).png?raw=true)

**Comment by CaelumD25** [comment]
The overall navbar is functional and implemented with bootstrap, currently adding more interactivity such as tooltips and hover animations.

TODO:
- Add interactivity
- Add more information

**Comment by CaelumD25** [comment]
Mostly meets criteria, some conflict with tooltips doesn't allow me to add tooltips without breaking mobile functionallity. However, hovering over the buttons with a mouse does still give you a description. Mobile has full text descriptions next to the buttons.

Open to suggestions if it is felt that the icons do not provide enough description on their own.
