### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by AmandaGAnderson** [VikeLabs/RateMyCoop#3]
### Task
As a user I would like a place to find out more information about RateMyCoop and VikeLabs. Prefer it to not be persistent, and have it only show when scrolled to the bottom of the page.

### Acceptance Criteria
- Link VikeLabs website and RateMyCoop Github 
- Link to blank pages for "About Us" and "Help"

### MockUp
![Home Mockup](https://github.com/VikeLabs/RateMyCoop/blob/main/Mockups/Home%20Page(Caelum%20V1).png?raw=true)

**Comment by CaelumD25** [comment]
Done, matches the above model. 
Would like to make the links wrap on smaller devices but this may not be an issue unless you're using somthing like the galaxy flip.
